coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 1%
    patch:
      default:
        target: 97%
        threshold: 1%

ignore:
  - "*.py"
  - "tests/*.py"
  - "gpflow/ci_utils.py"
  - "gpflow/versions.py"
  - "doc/source/notebooks/*"
