coverage:
  status:
    project:
      default:
        target: 97%
        threshold: 1%
    patch:
      default:
        target: 97%
        threshold: 1%

ignore:
  - "*.py"
  - "tests/*.py"
  - "gpflow/training/external_optimizer.py"
