from gpflow.models.model import Model
from gpflow.models.model import GPModel
from gpflow.models.gpr import GPR
from gpflow.models.gpmc import GPMC
from gpflow.models.gplvm import GPLVM
from gpflow.models.gplvm import BayesianGPLVM
from gpflow.models.sgpmc import SGPMC
from gpflow.models.sgpr import SGPRUpperMixin
from gpflow.models.sgpr import SGPR
from gpflow.models.sgpr import GPRFITC
from gpflow.models.svgp import SVGP
from gpflow.models.vgp import VGP_opper_archambeau
